version: "3.5"

services:
  backend-app:
    build: .
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    ports:
      - 3003:3003
  db:
    image: pingpong-db:latest-2
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: db