version: "3.5"

services:
  backend-app:
    image: j0ne/pingpong:rest-db-3
    environment: 
      - DB_USER=api_user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=kube_db
    depends_on:
      - db
    ports:
      - 3003:3003
  db:
    image: j0ne/pingpong-db:latest-2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
        - postgres:/var/lib/postgresql/data
    container_name: db