apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: project-todo
  name: project1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pingpong-dep
  minReplicas: 1
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 40
        periodSeconds: 10
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max