kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: devops-w-kube
  name: postgres-pv-volume
  labels:
    type: local
    app: pingpong-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: devops-w-kube
  name: postgres-pv-claim
  labels:
    app: pingpong-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi